name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.1.1435
          lein: 2.11.2
          boot: latest

      - name: Install Babashka
        run: |
          curl -sLO https://github.com/babashka/babashka/releases/download/v1.3.190/babashka-1.3.190-linux-amd64.tar.gz
          tar -xzf babashka-*-linux-amd64.tar.gz
          sudo mv bb /usr/local/bin/
          bb --version

      - name: Cache Clojure deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
            ~/.clojure
          key: clj-${{ runner.os }}-${{ hashFiles('deps.edn') }}
          restore-keys: |
            clj-${{ runner.os }}-

      - name: Run tests
        run: ./tests/run_tests.clj
